blog/config/routes.rb
Rails.application.routes.draw do

  get 'homes/show'

  get 'welcome/index'
  get 'welcome/members'
  get '/welcome/Farahat.html.erb', to: 'welcome#Farahat'
  get '/welcome/Amr.html.erb', to: 'welcome#Amr'
  get '/welcome/haidy.html.erb', to: 'welcome#haidy'
  get '/welcome/mira.html.erb', to: 'welcome#mira'
  get '/welcome/caroline.html.erb', to: 'welcome#caroline'
  get '/welcome/Shereen.html.erb', to: 'welcome#Shereen'
  devise_for :models
  devise_for :users

  resources :articles
   root 'welcome#index'

  resources :articles do
  resources :comments
end

end

blog/app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

blog/app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

blog/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  protect_from_forgery with: :exception
  
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
   #http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
  #http_basic_authenticate_with name: "dhh", password: "secret", only: :create
    def index
    @articles = Article.all
  end
     def show
    @article = Article.find(params[:id])
  end
  
  def new
  @article = Article.new
end
def edit
  @article = Article.find(params[:id])
end

  def create
@article = Article.new(article_params)

if @article.save
redirect_to @article
else
render 'new'
end
end

def update
  @article = Article.find(params[:id])
 
  if @article.update(article_params)
    redirect_to @article
  else
    render 'edit'
  end
end 

def destroy
  @article = Article.find(params[:id])
  @article.destroy
 
  redirect_to articles_path
end

private
  def article_params
    params.require(:article).permit(:title, :text)
    
  end
end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  #http_basic_authenticate_with name: "dhh", password: "secret", only: :create
  #http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
  
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
 
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

blog/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
  end
end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def members
  	
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/homes_helper.rb
module HomesHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

blog/app/views/articles/edit.html.erb
<!DOCTYPE html>
<head>
<title>Blog</title>
<link href="/normalize.css" rel="stylesheet">
<style>

header {
text-align: center;
background-size: cover;
color: rgb(000);
background background-repeat: no-repeat;


}
body {
text-align: center;
color: rgb(000);
font-family: Berlin Sans FB;
font-size: 20px;
color: #FF6600;
margin-right: 10%;
margin-left: 10%;
}
a{
color: black;
font-size: 20px;
font-family: Berlin Sans FB;


}
h1 {
font-size: 70px;

}

img{
margin: 40px 0px 0px 0px;
border: 7px solid black;
border-radius: 20px;

}

li {
display:inline;
padding: 0px 10px 0px 10px;
}
p{
text-align: center;
color: black;
border: 10;
font-family: Berlin Sans FB;
font-size: 30px;

}
ul {
padding:10px;

background: white;
}
li {
display:inline;
padding: 30px;
}
p2 {
	text-align: center;
color: black;
border: 10;
font-family: Berlin Sans FB;
font-size: 26px;

p3 {
	text-align: center;
color: black;
border: 10;
font-family: Berlin Sans FB;
font-size: 26px;

}


</style>
</head>
<body>
<header>
<img src = "https://scontent-lhr.xx.fbcdn.net/hphotos-xfp1/v/t1.0-9/p173x172/11006380_439477249537648_3831387245294219827_n.png?oh=238ba33880e70cddfdb0bba08cf7723c&oe=558522F5" align="center">
<ul>

<h1>Edit article</h1>
 

 <%= render 'form' %>	
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="fb-share-button" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button_count"></div>

<a class="twitter-share-button"
  href="https://twitter.com/share">
Tweet
</a>
<script>
window.twttr=(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],t=window.twttr||{};
if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);t._e=[];t.ready=function(f){t._e.push(f);};return t;}
(document,"script","twitter-wjs"));
</script>
<script src="https://apis.google.com/js/platform.js" async defer></script> <g:plus action="share"> </g:plus>

</ul>
<%= link_to 'Back', articles_path %>
</header>
<article>
<div1>

</div1>
</p>

<p> Follow </p>
<header>
<a href ="https://twitter.com/TheCode_Factory" > <img src ="https://cdn2.iconfinder.com/data/icons/metro-ui-icon-set/512/Twitter_alt_4.png" width="90" height="70" >
  <a href = "https://www.youtube.com/channel/UCn-CLnROwqKw-i8AQD1hdlg" > <img src ="http://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Youtube_icon.svg/256px-Youtube_icon.svg.png" width="90" height="70" >
  <a href = "https://plus.google.com/b/107105246190532748347/107105246190532748347/posts" > <img src = "http://icons.iconarchive.com/icons/uiconstock/socialmedia/512/Google-Plus-icon.png"width="90" height="70" >
  <a href = "https://www.facebook.com/codefactorycode" > <img src ="http://icons.iconarchive.com/icons/danleech/simple/512/facebook-icon.png" width ="90" height= "70" >
</article>

</body>

blog/app/views/articles/index.html.erb
<!DOCTYPE html>
<head>
<title>Blog</title>
<link href="/normalize.css" rel="stylesheet">
<style>

header {
text-align: center;
background-size: cover;
color: rgb(000);
background background-repeat: no-repeat;


}
body {
text-align: center;
color: rgb(000);
font-family: Berlin Sans FB;
font-size: 20px;
color: #FF6600;
margin-right: 10%;
margin-left: 10%;
}
a{
color: black;
font-size: 20px;
font-family: Berlin Sans FB;


}
h1 {
font-size: 70px;

}

img{
margin: 40px 0px 0px 0px;
border: 7px solid black;
border-radius: 20px;

}

li {
display:inline;
padding: 0px 10px 0px 10px;
}

ul {
padding:15px;

background: white;
}
li {
display:inline;
padding: 30px;
}
h1{
  text-align: center;
color: solid orange;
font-family: Times;
font-size: 50px;

}

p{
  font-size: 30px;
  text-align:center;
  font-family: Arial black;
}
</style>
</head>
<body>
<header>
<img src = "https://scontent-lhr.xx.fbcdn.net/hphotos-xfp1/v/t1.0-9/p173x172/11006380_439477249537648_3831387245294219827_n.png?oh=238ba33880e70cddfdb0bba08cf7723c&oe=558522F5" align="center">
<ul>
<li><a href="#">Our Projects</a></li>
<a href="<%= url_for controller: 'welcome', action: 'members' %>" style=" position:relative; top:-0.5px;left:-12px; right:50px; width:100px; height:25px;font-size:15pt; color:black;" >Our Members</a>
<li><a href="blog.html">Blog</a></li>
</ul>

</header>
<article>
<div1>
<center> <h1>Posts</h1>

<%= link_to 'New article', new_article_path %>

<table style="width:80%">
  <tr>
    <th>Title</th>
<th>Text</th>

    <th colspan="3"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Post comment', article_path(article) %></td>
      
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure you want to delete?' } %></td>
    </tr>
  <% end %>
</table>
</center>
</div1>
</p>

 <p> Follow us </p>
<header>
<a href ="https://twitter.com/TheCode_Factory" > <img src ="https://cdn2.iconfinder.com/data/icons/metro-ui-icon-set/512/Twitter_alt_4.png" width="90" height="70" >
  <a href = "https://www.youtube.com/channel/UCn-CLnROwqKw-i8AQD1hdlg" > <img src ="http://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Youtube_icon.svg/256px-Youtube_icon.svg.png" width="90" height="70" >
  <a href = "https://plus.google.com/b/107105246190532748347/107105246190532748347/posts" > <img src = "http://icons.iconarchive.com/icons/uiconstock/socialmedia/512/Google-Plus-icon.png"width="90" height="70" >
  <a href = "https://www.facebook.com/codefactorycode" > <img src ="http://icons.iconarchive.com/icons/danleech/simple/512/facebook-icon.png" width ="90" height= "70" >
</article>

</body>

blog/app/views/articles/new.html.erb
 <!DOCTYPE html>
<head>
<title>Blog</title>
<link href="/normalize.css" rel="stylesheet">
<style>

header {
text-align: center;
background-size: cover;
color: rgb(000);
background background-repeat: no-repeat;


}
body {
text-align: center;
color: rgb(000);
font-family: Berlin Sans FB;
font-size: 20px;
color: #FF6600;
margin-right: 10%;
margin-left: 10%;
}
a{
color: black;
font-size: 20px;
font-family: Berlin Sans FB;


}
h1 {
font-size: 70px;

}

img{
margin: 40px 0px 0px 0px;
border: 7px solid black;
border-radius: 20px;

}

li {
display:inline;
padding: 0px 10px 0px 10px;
}
p{
  font-size: 30px;
  text-align:center;
  font-family: Arial black;

ul {
padding:10px;

background: white;
}
li {
display:inline;
padding: 30px;
}
p2 {
	text-align: center;
color: black;
border: 10;
font-family: Berlin Sans FB;
font-size: 26px;

p3 {
	text-align: center;
color: black;
border: 10;
font-family: Berlin Sans FB;
font-size: 26px;

}


</style>
</head>
<body>
<header>
<img src = "https://scontent-lhr.xx.fbcdn.net/hphotos-xfp1/v/t1.0-9/p173x172/11006380_439477249537648_3831387245294219827_n.png?oh=238ba33880e70cddfdb0bba08cf7723c&oe=558522F5" align="center">

<ul>
<h1>New article</h1>

</ul>


<%= render 'form' %>	
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="fb-share-button" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button_count"></div>

<a class="twitter-share-button"
  href="https://twitter.com/share">
Tweet
</a>
<script>
window.twttr=(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],t=window.twttr||{};
if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);t._e=[];t.ready=function(f){t._e.push(f);};return t;}
(document,"script","twitter-wjs"));
</script>
<script src="https://apis.google.com/js/platform.js" async defer></script> <g:plus action="share"> </g:plus>

 
</header>
<%= link_to 'Back', articles_path %>

 <p> Follow us </p>
<header>
<a href ="https://twitter.com/TheCode_Factory" > <img src ="https://cdn2.iconfinder.com/data/icons/metro-ui-icon-set/512/Twitter_alt_4.png" width="90" height="70" >
  <a href = "https://www.youtube.com/channel/UCn-CLnROwqKw-i8AQD1hdlg" > <img src ="http://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Youtube_icon.svg/256px-Youtube_icon.svg.png" width="90" height="70" >
  <a href = "https://plus.google.com/b/107105246190532748347/107105246190532748347/posts" > <img src = "http://icons.iconarchive.com/icons/uiconstock/socialmedia/512/Google-Plus-icon.png"width="90" height="70" >
  <a href = "https://www.facebook.com/codefactorycode" > <img src ="http://icons.iconarchive.com/icons/danleech/simple/512/facebook-icon.png" width ="90" height= "70" >
</article>

</body>

blog/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
 
<h2>Comments</h2>
<%= render @article.comments %>
 
<h2>Add a comment:</h2>
<%= render 'comments/form' %>
 
<%= link_to 'Edit Article', edit_article_path(@article) %> |
<%= link_to 'Back to Articles', articles_path %>

blog/app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>

</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
 
<p>
 <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p> 

blog/app/views/comments/_form.html.erb
<!DOCTYPE html>

<head>
<title>Blog</title>
<link href="/normalize.css" rel="stylesheet">

<style>

header {
text-align: center;
background-size: cover;
color: rgb(000);
background background-repeat: no-repeat;


}
body {
text-align: center;
color: rgb(000);
font-family: Berlin Sans FB;
font-size: 20px;
color: #FF6600;
margin-right: 10%;
margin-left: 10%;
}
a{
color: black;
font-size: 20px;
font-family: Berlin Sans FB;


}
h1 {
font-size: 70px;

}

img{
margin: 40px 0px 0px 0px;
border: 7px solid black;
border-radius: 20px;

}

li {
display:inline;
padding: 0px 10px 0px 10px;
}
p{
text-align: center;
color: black;
border: 10;
font-family: Berlin Sans FB;
font-size: 30px;

}
ul {
padding:10px;

background: white;
}
li {
display:inline;
padding: 30px;
}
p2 {
  text-align: center;
color: orange;
border: 10 ;
font-family: Berlin Sans FB;
font-size: 26px;
}



</style>
</head>
<!-- <img src = "https://scontent-lhr.xx.fbcdn.net/hphotos-xfp1/v/t1.0-9/p173x172/11006380_439477249537648_3831387245294219827_n.png?oh=238ba33880e70cddfdb0bba08cf7723c&oe=558522F5" align="center"> -->
<body>

<header>



<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>



  
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="fb-share-button" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button_count"></div>

<a class="twitter-share-button"
  href="https://twitter.com/share">
Tweet
</a>
<script>
window.twttr=(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],t=window.twttr||{};
if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);t._e=[];t.ready=function(f){t._e.push(f);};return t;}
(document,"script","twitter-wjs"));
</script>
<script src="https://apis.google.com/js/platform.js" async defer></script> <g:plus action="share"> </g:plus>

</body>

</header>

blog/app/views/homes/show.html.erb
<h1>Homes#show</h1>
<p>Find me in app/views/homes/show.html.erb</p>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<style>

</style>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit your profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  
<% end %>
</body>
</html>

blog/app/views/welcome/Amr.html.erb
<!DOCTYPE html>
<head>
<title>Amr El Assar's profile</title>
<link href="/normalize.css" rel="stylesheet">
<style>

header {
  text-align: center;
  background-size: cover;
  color: rgb(000);
  background background-repeat: no-repeat;


}
body {
    text-align: center;
     color: rgb(000);
     font-family: Berlin Sans FB;
    font-size: 20px;
    color: #FF6600;
    margin-right: 10%;
    margin-left: 10%;
   
}
a{
  color: black;
  font-size: 20px;
  font-family: Berlin Sans FB;


}
h1 {
  font-size: 70px;

}

img{
  margin: 40px 0px 0px 0px;
  border: 7px solid black;
  border-radius: 20px;
  
}

li {
  display:inline;
  padding: 0px 10px 0px 10px;
}
p{
     text-align: center;
     color: black;
     border: 10;
     font-family: Berlin Sans FB;
    font-size: 30px;
    }
    ul {
  padding:10px;

  background: white;
}
li {
  display:inline;
  padding: 30px;
}
h{
   font-size: 70px;
}



</style>
</head>
<body>
  <header>
  <img src = "https://scontent-lhr.xx.fbcdn.net/hphotos-xfp1/v/t1.0-9/p173x172/11006380_439477249537648_3831387245294219827_n.png?oh=238ba33880e70cddfdb0bba08cf7723c&oe=558522F5" align="center">

        <ul>
      
       <br>
       <img src='https://scontent-lhr.xx.fbcdn.net/hphotos-xpa1/v/t1.0-9/17903_10151547751527148_2084458155_n.jpg?oh=de117736a253ba32aea6618aa9db5810&oe=5594DD72' width="210" height="270" >
  <br>

  <h>Amr ElAasar</h>

    </ul>

  </header>
  <article>
  <p> Follow us </p>
  <header>
  <a href ="https://twitter.com/TheCode_Factory" > <img src ="https://cdn2.iconfinder.com/data/icons/metro-ui-icon-set/512/Twitter_alt_4.png" width="90" height="70" >
  <a href = "https://www.youtube.com/channel/UCn-CLnROwqKw-i8AQD1hdlg" > <img src ="http://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Youtube_icon.svg/256px-Youtube_icon.svg.png" width="90" height="70" >
  <a href = "https://plus.google.com/b/107105246190532748347/107105246190532748347/posts" > <img src = "http://icons.iconarchive.com/icons/uiconstock/socialmedia/512/Google-Plus-icon.png"width="90" height="70" >
  <a href = "https://www.facebook.com/codefactorycode" > <img src ="http://icons.iconarchive.com/icons/danleech/simple/512/facebook-icon.png" width ="90" height= "70" > 
  </article>

</body>

blog/app/views/welcome/Farahat.html.erb
<!DOCTYPE html>
<head>
<title>Ahmed Farahat's profile</title>
<link href="/normalize.css" rel="stylesheet">
<style>

header {
  text-align: center;
  background-size: cover;
  color: rgb(000);
  background background-repeat: no-repeat;


}
body {
    text-align: center;
     color: rgb(000);
     font-family: Berlin Sans FB;
    font-size: 20px;
    color: #FF6600;
    margin-right: 10%;
    margin-left: 10%;
   
}
a{
  color: black;
  font-size: 20px;
  font-family: Berlin Sans FB;


}
h1 {
  font-size: 70px;

}

img{
  margin: 40px 0px 0px 0px;
  border: 7px solid black;
  border-radius: 20px;
  
}

li {
  display:inline;
  padding: 0px 10px 0px 10px;
}
p{
     text-align: center;
     color: black;
     border: 10;
     font-family: Berlin Sans FB;
    font-size: 30px;
    }
    ul {
  padding:10px;

  background: white;
}
li {
  display:inline;
  padding: 30px;
}
h{
   font-size: 70px;
}



</style>
</head>
<body>
  <header>
  <img src = "https://scontent-lhr.xx.fbcdn.net/hphotos-xfp1/v/t1.0-9/p173x172/11006380_439477249537648_3831387245294219827_n.png?oh=238ba33880e70cddfdb0bba08cf7723c&oe=558522F5" align="center">

        <ul>
      

       <br>
       <img src='https://scontent-lhr.xx.fbcdn.net/hphotos-xfp1/v/t1.0-9/10551084_10153044793835874_3287537384530892757_n.jpg?oh=c14c6fadac93ceb6f92a1814a942bfb0&oe=554BFDCA' width="210" height="270" >
  <br>

  <h>Ahmed Farahat</h>

    </ul>

  </header>
  <article>

  <p> Follow us</p>
  <header>
  <a href ="https://twitter.com/TheCode_Factory" > <img src ="https://cdn2.iconfinder.com/data/icons/metro-ui-icon-set/512/Twitter_alt_4.png" width="90" height="70" >
  <a href = "https://www.youtube.com/channel/UCn-CLnROwqKw-i8AQD1hdlg" > <img src ="http://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Youtube_icon.svg/256px-Youtube_icon.svg.png" width="90" height="70" >
  <a href = "https://plus.google.com/b/107105246190532748347/107105246190532748347/posts" > <img src = "http://icons.iconarchive.com/icons/uiconstock/socialmedia/512/Google-Plus-icon.png"width="90" height="70" >
  <a href = "https://www.facebook.com/codefactorycode" > <img src ="http://icons.iconarchive.com/icons/danleech/simple/512/facebook-icon.png" width ="90" height= "70" >
  </article>

</body>